# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
name: Ruby CI

on:
  # Always run post-merge on "main" branch
  push:
    branches: [ "main" ]
  # And for Every PR against "main"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      env:
        BUNDLER_WITH: development
      with:
        ruby-version: '3.2'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # Checks to see if any files in the PR match one of the listed file types.
    # We can use this filter to decide whether or not to run linters or tests.
    # This will return true if there's a markdown file that was changed
    # in the PR.
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'shell'
        filters: |
          rb_scripts_filter:
            - added|modified: '**/*.rb'
    - name: Run Rubocop validations
      if: ${{ steps.filter.outputs.rb_scripts_filter == 'true' }}
      run: bundle exec rubocop ${{ steps.filter.outputs.rb_scripts_filter_files}}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
    - uses: actions/checkout@v4
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      env:
        BUNDLER_WITH: test
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run RSpec tests
      run: bundle exec rspec -fd
